GET http://localhost:8080/api/products
Content-Type: application/json

{
    "id": 30,
    "name": "iPhone 16",
    "description": "Latest Apple phone",
    "price": 3600.0,
    "stock": 200,
    "imgUrl": "iphone16.jpg"
  },
